# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f844332c6580b70b6031cafc6da6cec94aec947a3eb8fd04aedccc6a8537761b596bd0b288a80bec6706186464fcbab156f7678401c413e9d532c7edd1c2c37a

test:
  secret_key_base: da4bc8a832815808696719f8f87b9c0dc7e4018473734186777ab44443e94c8dbf2a702e88406781debdcbe747be9116cc7b3aadd055dd4f5849a719efb09508

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
